

name: Changelog

on: 
  push:
    branches: ["PRTC-3"]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: Configure committer
      run: |
        git config user.name "Github Actions"
        git config user.email "<>"
    
    - name: Standard version
    - uses: qzb/standard-version@v1.0.5