
name: Generate Changelog

on:
  push:
    branches: ["PRTC-3"]

jobs: 
  generate-changelog: 
    runs-on: ubuntu-latest

    steps:
      - name: Install dependecies
        run: npm install
      - name: Run standard version
        run: npm run release